// Raw project parameters
export const PROJECT_PARAMS = {
  goal: 600,
  weeksTotal: 4,
  snapshotWeek: 2,
  trainerWeeklyHourCap: 30,
  reviewerWeeklyHourCap: 60,
  hoursToWrite: 6,
  hoursToReview: 2,
  hoursToRevise: 1.5,
  expectedRevisionCycles: 2,
};

// Trainer data — columns:
// id, claimed, completed, fixingDone, needsWork, signedOff, minorIssues, majorIssues
export const TRAINERS = [
  { id: "Trainer1",  claimed: 6,  completed: 21, fixingDone: 0,  needsWork: 8,  signedOff: 0,  minorIssues: 21,  majorIssues: 42  },
  { id: "Trainer2",  claimed: 6,  completed: 6,  fixingDone: 2,  needsWork: 5,  signedOff: 0,  minorIssues: 8,   majorIssues: 26  },
  { id: "Trainer3",  claimed: 5,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer4",  claimed: 6,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer5",  claimed: 6,  completed: 5,  fixingDone: 2,  needsWork: 3,  signedOff: 0,  minorIssues: 4,   majorIssues: 49  },
  { id: "Trainer6",  claimed: 8,  completed: 8,  fixingDone: 3,  needsWork: 6,  signedOff: 2,  minorIssues: 7,   majorIssues: 50  },
  { id: "Trainer7",  claimed: 9,  completed: 6,  fixingDone: 3,  needsWork: 3,  signedOff: 0,  minorIssues: 7,   majorIssues: 22  },
  { id: "Trainer8",  claimed: 9,  completed: 8,  fixingDone: 3,  needsWork: 5,  signedOff: 3,  minorIssues: 17,  majorIssues: 48  },
  { id: "Trainer9",  claimed: 2,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer10", claimed: 2,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer11", claimed: 17, completed: 17, fixingDone: 3,  needsWork: 5,  signedOff: 0,  minorIssues: 31,  majorIssues: 28  },
  { id: "Trainer12", claimed: 2,  completed: 2,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer13", claimed: 47, completed: 6,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 1,   majorIssues: 21  },
  { id: "Trainer14", claimed: 12, completed: 11, fixingDone: 5,  needsWork: 9,  signedOff: 3,  minorIssues: 23,  majorIssues: 158 },
  { id: "Trainer15", claimed: 2,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer16", claimed: 5,  completed: 5,  fixingDone: 2,  needsWork: 5,  signedOff: 0,  minorIssues: 6,   majorIssues: 24  },
  { id: "Trainer17", claimed: 2,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer18", claimed: 5,  completed: 3,  fixingDone: 3,  needsWork: 3,  signedOff: 2,  minorIssues: 2,   majorIssues: 24  },
  { id: "Trainer19", claimed: 14, completed: 20, fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer20", claimed: 3,  completed: 2,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 3,   majorIssues: 4   },
  { id: "Trainer21", claimed: 11, completed: 8,  fixingDone: 6,  needsWork: 6,  signedOff: 3,  minorIssues: 15,  majorIssues: 49  },
  { id: "Trainer22", claimed: 6,  completed: 3,  fixingDone: 2,  needsWork: 3,  signedOff: 2,  minorIssues: 9,   majorIssues: 17  },
  { id: "Trainer23", claimed: 3,  completed: 2,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 0,   majorIssues: 20  },
  { id: "Trainer24", claimed: 15, completed: 14, fixingDone: 0,  needsWork: 3,  signedOff: 0,  minorIssues: 14,  majorIssues: 2   },
  { id: "Trainer25", claimed: 6,  completed: 5,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer26", claimed: 5,  completed: 5,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 2,   majorIssues: 29  },
  { id: "Trainer27", claimed: 6,  completed: 5,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 35,  majorIssues: 7   },
  { id: "Trainer28", claimed: 9,  completed: 3,  fixingDone: 5,  needsWork: 3,  signedOff: 5,  minorIssues: 1,   majorIssues: 46  },
  { id: "Trainer29", claimed: 5,  completed: 2,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 0,   majorIssues: 18  },
  { id: "Trainer30", claimed: 5,  completed: 3,  fixingDone: 2,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer31", claimed: 3,  completed: 3,  fixingDone: 3,  needsWork: 3,  signedOff: 2,  minorIssues: 7,   majorIssues: 16  },
  { id: "Trainer32", claimed: 9,  completed: 6,  fixingDone: 3,  needsWork: 5,  signedOff: 3,  minorIssues: 13,  majorIssues: 29  },
  { id: "Trainer33", claimed: 6,  completed: 2,  fixingDone: 2,  needsWork: 2,  signedOff: 2,  minorIssues: 17,  majorIssues: 12  },
  { id: "Trainer34", claimed: 14, completed: 23, fixingDone: 3,  needsWork: 0,  signedOff: 2,  minorIssues: 1,   majorIssues: 0   },
  { id: "Trainer35", claimed: 8,  completed: 3,  fixingDone: 2,  needsWork: 3,  signedOff: 0,  minorIssues: 28,  majorIssues: 13  },
  { id: "Trainer36", claimed: 9,  completed: 9,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 7,   majorIssues: 9   },
  { id: "Trainer37", claimed: 12, completed: 9,  fixingDone: 5,  needsWork: 6,  signedOff: 2,  minorIssues: 18,  majorIssues: 87  },
  { id: "Trainer38", claimed: 12, completed: 8,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer39", claimed: 8,  completed: 0,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 39,  majorIssues: 12  },
  { id: "Trainer40", claimed: 8,  completed: 6,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 1,   majorIssues: 9   },
  { id: "Trainer41", claimed: 9,  completed: 5,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 0,   majorIssues: 14  },
  { id: "Trainer42", claimed: 2,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer43", claimed: 9,  completed: 2,  fixingDone: 3,  needsWork: 3,  signedOff: 2,  minorIssues: 13,  majorIssues: 7   },
  { id: "Trainer44", claimed: 32, completed: 12, fixingDone: 5,  needsWork: 3,  signedOff: 0,  minorIssues: 9,   majorIssues: 25  },
  { id: "Trainer45", claimed: 5,  completed: 3,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer46", claimed: 6,  completed: 5,  fixingDone: 5,  needsWork: 6,  signedOff: 3,  minorIssues: 21,  majorIssues: 46  },
  { id: "Trainer47", claimed: 6,  completed: 3,  fixingDone: 2,  needsWork: 3,  signedOff: 2,  minorIssues: 36,  majorIssues: 27  },
  { id: "Trainer48", claimed: 14, completed: 15, fixingDone: 3,  needsWork: 2,  signedOff: 2,  minorIssues: 8,   majorIssues: 7   },
  { id: "Trainer49", claimed: 6,  completed: 14, fixingDone: 3,  needsWork: 6,  signedOff: 6,  minorIssues: 14,  majorIssues: 2   },
  { id: "Trainer50", claimed: 3,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer51", claimed: 6,  completed: 2,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 0,   majorIssues: 6   },
  { id: "Trainer52", claimed: 0,  completed: 12, fixingDone: 8,  needsWork: 2,  signedOff: 0,  minorIssues: 3,   majorIssues: 23  },
  { id: "Trainer53", claimed: 24, completed: 23, fixingDone: 9,  needsWork: 9,  signedOff: 6,  minorIssues: 22,  majorIssues: 49  },
  { id: "Trainer54", claimed: 8,  completed: 12, fixingDone: 5,  needsWork: 11, signedOff: 3,  minorIssues: 7,   majorIssues: 39  },
  { id: "Trainer55", claimed: 6,  completed: 5,  fixingDone: 3,  needsWork: 3,  signedOff: 0,  minorIssues: 3,   majorIssues: 7   },
  { id: "Trainer56", claimed: 26, completed: 12, fixingDone: 8,  needsWork: 8,  signedOff: 5,  minorIssues: 11,  majorIssues: 21  },
  { id: "Trainer57", claimed: 3,  completed: 3,  fixingDone: 2,  needsWork: 2,  signedOff: 2,  minorIssues: 37,  majorIssues: 14  },
  { id: "Trainer58", claimed: 11, completed: 3,  fixingDone: 3,  needsWork: 5,  signedOff: 0,  minorIssues: 25,  majorIssues: 30  },
  { id: "Trainer59", claimed: 2,  completed: 0,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer60", claimed: 5,  completed: 3,  fixingDone: 3,  needsWork: 3,  signedOff: 2,  minorIssues: 4,   majorIssues: 12  },
  { id: "Trainer61", claimed: 12, completed: 2,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer62", claimed: 21, completed: 20, fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 0,   majorIssues: 1   },
  { id: "Trainer63", claimed: 8,  completed: 6,  fixingDone: 2,  needsWork: 3,  signedOff: 2,  minorIssues: 16,  majorIssues: 13  },
  { id: "Trainer64", claimed: 6,  completed: 5,  fixingDone: 3,  needsWork: 5,  signedOff: 0,  minorIssues: 18,  majorIssues: 42  },
  { id: "Trainer65", claimed: 20, completed: 17, fixingDone: 3,  needsWork: 2,  signedOff: 2,  minorIssues: 1,   majorIssues: 0   },
  { id: "Trainer66", claimed: 5,  completed: 2,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 8,   majorIssues: 34  },
  { id: "Trainer67", claimed: 0,  completed: 8,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer68", claimed: 5,  completed: 2,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer69", claimed: 3,  completed: 2,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer70", claimed: 5,  completed: 2,  fixingDone: 2,  needsWork: 2,  signedOff: 2,  minorIssues: 4,   majorIssues: 16  },
  { id: "Trainer71", claimed: 3,  completed: 14, fixingDone: 2,  needsWork: 8,  signedOff: 3,  minorIssues: 5,   majorIssues: 9   },
  { id: "Trainer72", claimed: 8,  completed: 5,  fixingDone: 2,  needsWork: 2,  signedOff: 0,  minorIssues: 0,   majorIssues: 6   },
  { id: "Trainer73", claimed: 9,  completed: 5,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 2,   majorIssues: 9   },
  { id: "Trainer74", claimed: 6,  completed: 6,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 4,   majorIssues: 10  },
  { id: "Trainer75", claimed: 17, completed: 14, fixingDone: 11, needsWork: 12, signedOff: 5,  minorIssues: 35,  majorIssues: 139 },
  { id: "Trainer76", claimed: 20, completed: 6,  fixingDone: 2,  needsWork: 2,  signedOff: 2,  minorIssues: 4,   majorIssues: 12  },
  { id: "Trainer77", claimed: 12, completed: 14, fixingDone: 6,  needsWork: 8,  signedOff: 9,  minorIssues: 12,  majorIssues: 10  },
  { id: "Trainer78", claimed: 3,  completed: 2,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 5,   majorIssues: 9   },
  { id: "Trainer79", claimed: 3,  completed: 2,  fixingDone: 0,  needsWork: 2,  signedOff: 0,  minorIssues: 5,   majorIssues: 7   },
  { id: "Trainer80", claimed: 5,  completed: 2,  fixingDone: 3,  needsWork: 3,  signedOff: 0,  minorIssues: 7,   majorIssues: 26  },
  { id: "Trainer81", claimed: 20, completed: 11, fixingDone: 8,  needsWork: 8,  signedOff: 6,  minorIssues: 18,  majorIssues: 68  },
  { id: "Trainer82", claimed: 6,  completed: 2,  fixingDone: 0,  needsWork: 0,  signedOff: 0,  minorIssues: 0,   majorIssues: 0   },
  { id: "Trainer83", claimed: 12, completed: 12, fixingDone: 6,  needsWork: 9,  signedOff: 2,  minorIssues: 41,  majorIssues: 52  },
  { id: "Trainer84", claimed: 6,  completed: 3,  fixingDone: 5,  needsWork: 3,  signedOff: 2,  minorIssues: 17,  majorIssues: 26  },
  { id: "Trainer85", claimed: 14, completed: 12, fixingDone: 0,  needsWork: 0,  signedOff: 3,  minorIssues: 1,   majorIssues: 1   },
];

// Reviewer data
export const REVIEWERS = [
  { id: "Reviewer1",  reviewsCompleted: 80,  minorIssues: 68,  majorIssues: 119, status: "OVER"  },
  { id: "Reviewer2",  reviewsCompleted: 8,   minorIssues: 3,   majorIssues: 1,   status: "UNDER" },
  { id: "Reviewer3",  reviewsCompleted: 95,  minorIssues: 100, majorIssues: 290, status: "OVER"  },
  { id: "Reviewer4",  reviewsCompleted: 8,   minorIssues: 9,   majorIssues: 24,  status: "UNDER" },
  { id: "Reviewer5",  reviewsCompleted: 13,  minorIssues: 5,   majorIssues: 6,   status: "UNDER" },
  { id: "Reviewer6",  reviewsCompleted: 103, minorIssues: 53,  majorIssues: 173, status: "OVER"  },
  { id: "Reviewer7",  reviewsCompleted: 75,  minorIssues: 19,  majorIssues: 128, status: "OVER"  },
  { id: "Reviewer8",  reviewsCompleted: 60,  minorIssues: 24,  majorIssues: 16,  status: "UNDER" },
  { id: "Reviewer9",  reviewsCompleted: 20,  minorIssues: 4,   majorIssues: 21,  status: "UNDER" },
  { id: "Reviewer10", reviewsCompleted: 28,  minorIssues: 46,  majorIssues: 33,  status: "UNDER" },
  { id: "Reviewer11", reviewsCompleted: 20,  minorIssues: 12,  majorIssues: 67,  status: "UNDER" },
  { id: "Reviewer12", reviewsCompleted: 0,   minorIssues: 0,   majorIssues: 0,   status: "UNDER" },
  { id: "Reviewer13", reviewsCompleted: 65,  minorIssues: 35,  majorIssues: 28,  status: "OVER"  },
  { id: "Reviewer14", reviewsCompleted: 0,   minorIssues: 0,   majorIssues: 0,   status: "UNDER" },
  { id: "Reviewer15", reviewsCompleted: 15,  minorIssues: 6,   majorIssues: 19,  status: "UNDER" },
  { id: "Reviewer16", reviewsCompleted: 125, minorIssues: 131, majorIssues: 86,  status: "OVER"  },
  { id: "Reviewer17", reviewsCompleted: 58,  minorIssues: 7,   majorIssues: 160, status: "UNDER" },
  { id: "Reviewer18", reviewsCompleted: 68,  minorIssues: 59,  majorIssues: 64,  status: "OVER"  },
  { id: "Reviewer19", reviewsCompleted: 68,  minorIssues: 9,   majorIssues: 150, status: "OVER"  },
  { id: "Reviewer20", reviewsCompleted: 88,  minorIssues: 163, majorIssues: 305, status: "OVER"  },
];
